### ISSUE TITLE
python Visualization error

### ISSUE THREAD

**Issue by cosunae** [eth-cscs/serialbox2#147]
While trying to visualize field a2t

>>> a2t = serializer.read("a2t", constantsoint)
>>> Visualizer(a2t, "a2t")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/cosuna/serialbox2/build_gcc_gfortran/install/python/serialbox/visualizer.py", line 59, in __init__
    self.__jend = field.shape[1] - halospec[1][1]
IndexError: tuple index out of range

**Comment by cosunae** [comment]
I have quite some other bugs, 

from p_s_nnew in DycoreUnittest.DoStep-in

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/cosuna/serialbox2/build_gcc_gfortran/install/python/serialbox/visualizer.py", line 69, in __init__
    self.__slider = Slider(slideraxes, 'K level', 0, field.shape[2] - 1, valinit=0)
IndexError: tuple index out of range
